[auth]
GMAIL_SCOPE = ["https://www.googleapis.com/auth/gmail.readonly"]

[auth.gmail.credential]
installed.client_id="client-id-from-gcp-credential"
installed.project_id="your-gcp-project-id"
installed.auth_uri="gcp-auth-uri"
installed.token_uri="gcp-token-uri"
installed.auth_provider_x509_cert_url="gcp-auth-provider"
installed.client_secret="gcp-client-secret"
installed.redirect_uris=["gcp-redirect-uri"]

[auth.gmail]
token="path-to-your-token.json"


[info]
client_email="your-gmail-id"
financial_services=["your-bank-1", "your-bank-2"]

[auth.openai]
api_key = "Your-openai-api-key"


[auth.db.mongo]
connection_string="your-mongodb-connection-string"
